//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoCBuilder {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("IoCBuilder.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BuilderHasNoStrategies {
            get {
                return ResourceManager.GetString("BuilderHasNoStrategies", resourceCulture);
            }
        }
        
        internal static string BuilderStrategyTraceBuildUp {
            get {
                return ResourceManager.GetString("BuilderStrategyTraceBuildUp", resourceCulture);
            }
        }
        
        internal static string BuilderStrategyTraceTearDown {
            get {
                return ResourceManager.GetString("BuilderStrategyTraceTearDown", resourceCulture);
            }
        }
        
        internal static string BuildUpFinished {
            get {
                return ResourceManager.GetString("BuildUpFinished", resourceCulture);
            }
        }
        
        internal static string BuildUpStarting {
            get {
                return ResourceManager.GetString("BuildUpStarting", resourceCulture);
            }
        }
        
        internal static string CallingConstructor {
            get {
                return ResourceManager.GetString("CallingConstructor", resourceCulture);
            }
        }
        
        internal static string CallingMethod {
            get {
                return ResourceManager.GetString("CallingMethod", resourceCulture);
            }
        }
        
        internal static string CallingOnBuiltUp {
            get {
                return ResourceManager.GetString("CallingOnBuiltUp", resourceCulture);
            }
        }
        
        internal static string CallingOnTearingDown {
            get {
                return ResourceManager.GetString("CallingOnTearingDown", resourceCulture);
            }
        }
        
        internal static string CallingProperty {
            get {
                return ResourceManager.GetString("CallingProperty", resourceCulture);
            }
        }
        
        internal static string CannotCreateInstanceOfType {
            get {
                return ResourceManager.GetString("CannotCreateInstanceOfType", resourceCulture);
            }
        }
        
        internal static string CannotExtractTypeFromBuildKey {
            get {
                return ResourceManager.GetString("CannotExtractTypeFromBuildKey", resourceCulture);
            }
        }
        
        internal static string CannotInjectReadOnlyProperty {
            get {
                return ResourceManager.GetString("CannotInjectReadOnlyProperty", resourceCulture);
            }
        }
        
        internal static string DependencyMissing {
            get {
                return ResourceManager.GetString("DependencyMissing", resourceCulture);
            }
        }
        
        internal static string InvalidAttributeCombination {
            get {
                return ResourceManager.GetString("InvalidAttributeCombination", resourceCulture);
            }
        }
        
        internal static string InvalidEnumerationValue {
            get {
                return ResourceManager.GetString("InvalidEnumerationValue", resourceCulture);
            }
        }
        
        internal static string KeyAlreadyPresentInDictionary {
            get {
                return ResourceManager.GetString("KeyAlreadyPresentInDictionary", resourceCulture);
            }
        }
        
        internal static string MissingCreationPolicy {
            get {
                return ResourceManager.GetString("MissingCreationPolicy", resourceCulture);
            }
        }
        
        internal static string NoAppropriateConstructor {
            get {
                return ResourceManager.GetString("NoAppropriateConstructor", resourceCulture);
            }
        }
        
        internal static string ReflectedMember {
            get {
                return ResourceManager.GetString("ReflectedMember", resourceCulture);
            }
        }
        
        internal static string SingletonRegistered {
            get {
                return ResourceManager.GetString("SingletonRegistered", resourceCulture);
            }
        }
        
        internal static string SingletonReturned {
            get {
                return ResourceManager.GetString("SingletonReturned", resourceCulture);
            }
        }
        
        internal static string TearDownFinished {
            get {
                return ResourceManager.GetString("TearDownFinished", resourceCulture);
            }
        }
        
        internal static string TearDownStarting {
            get {
                return ResourceManager.GetString("TearDownStarting", resourceCulture);
            }
        }
        
        internal static string TypeMapped {
            get {
                return ResourceManager.GetString("TypeMapped", resourceCulture);
            }
        }
        
        internal static string TypeNotCompatible {
            get {
                return ResourceManager.GetString("TypeNotCompatible", resourceCulture);
            }
        }
    }
}
